package io.datapulse.marketplaces.endpoint;

public enum EndpointKey {

  // ===== Wildberries =====
  DICT_WB_WAREHOUSES_FBW,
  DICT_WB_OFFICES_FBS,
  DICT_WB_WAREHOUSES_SELLER,

  DICT_WB_CATEGORIES_PARENT,
  DICT_WB_SUBJECTS,

  DICT_WB_TARIFFS_COMMISSION,
  DICT_WB_PRODUCTS,

  FACT_WB_SALES_REPORT_DETAIL_BY_PERIOD,
  FACT_WB_SUPPLIER_SALES,

  FACT_WB_STOCKS,
  FACT_WB_INCOMES,

  // ===== Ozon =====
  DICT_OZON_WAREHOUSES_FBS,
  DICT_OZON_CLUSTERS,
  DICT_OZON_CATEGORY_TREE,

  DICT_OZON_PRODUCT_INFO_PRICES,
  DICT_OZON_PRODUCTS,
  DICT_OZON_PRODUCT_INFO_LIST,

  FACT_OZON_POSTING_FBO_LIST,
  FACT_OZON_POSTING_FBS_LIST,
  FACT_OZON_FINANCE_TRANSACTION_LIST,

  FACT_OZON_RETURNS_LIST,
  FACT_OZON_PRODUCT_INFO_STOCKS,
  FACT_OZON_ANALYTICS_STOCKS;

  public String tag() {
    return name().toLowerCase();
  }
}
