### Run ETL (last 30 days) WAREHOUSE
POST http://localhost:8080/api/etl/run
Content-Type: application/json

{
  "accountId": 6,
  "event": "WAREHOUSE",
  "from": "2025-10-22",
  "to": "2025-11-22",
  "burst": 1
}

> {%
  const now  = new Date();
  const to   = new Date(now.getFullYear(), now.getMonth(), now.getDate());
  const from = new Date(to.getTime() - 30*24*60*60*1000);
  function ymd(d){ return d.toISOString().slice(0,10); }
  client.global.set("from", ymd(from));
  client.global.set("to",   ymd(to));
%}
