spring:
  datasource:
    url: "jdbc:postgresql://127.0.0.1:5434/datapulse?reWriteBatchedInserts=true"
    username: "datapulse"
    password: "datapulse"
    hikari:
      schema: datapulse
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.jdbc.batch_size: 500
      hibernate.order_inserts: true
      hibernate.order_updates: true
  liquibase:
    enabled: true
    change-log: classpath:/db/master.xml
    default-schema: datapulse
    liquibase-schema: datapulse

webclient:
  max-in-memory-size: 5242880
  connect-timeout-millis: 10000
  response-timeout-seconds: 30
  read-timeout-seconds: 30
  write-timeout-seconds: 30

system-account:
  enabled: true
  name: DATAPULSE_SYSTEM
  connections:
    WILDBERRIES:
      active: true
      token: ${WB_SYSTEM_TOKEN}
    OZON:
      active: true
      client-id: ${OZON_SYSTEM_CLIENT_ID:}
      api-key: ${OZON_SYSTEM_API_KEY:}

sandbox-account:
  enabled: true
  name: DATAPULSE_SANDBOX
  connections:
    WILDBERRIES:
      active: true
      token: ${WB_SANDBOX_TOKEN:}

vault:
  uri: http://localhost:8300
  token: ${VAULT_TOKEN:}

app:
  user-activity:
    activity-window: PT5M
    max-size: 100_000
    cleanup-fixed-delay: PT1M
    flush-fixed-delay: PT1S
    flush-batch-size: 500
