spring:
  application:
    name: datapulse

  datasource:
    url: "jdbc:postgresql://127.0.0.1:5434/datapulse?currentSchema=datapulse&reWriteBatchedInserts=true"
    username: "datapulse"
    password: "datapulse"
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.default_schema: datapulse
      hibernate.format_sql: true
      hibernate.jdbc.batch_size: 500
      hibernate.jdbc.fetch_size: 200
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.generate_statistics: false
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:/db/master.xml
    default-schema: datapulse
    liquibase-schema: datapulse

webclient:
  max-in-memory-size: 262144
  connect-timeout-millis: 10000
  response-timeout-seconds: 30
  read-timeout-seconds: 30
  write-timeout-seconds: 30

crypto:
  master-key-base64: ${DATAPULSE_CRYPTO_MASTER_KEY_BASE64:}
  gcm-tag-length-bits: 128
