spring:
  application:
    name: datapulse

  datasource:
    url: "jdbc:postgresql://127.0.0.1:5434/datapulse?currentSchema=datapulse&reWriteBatchedInserts=true"
    username: "datapulse"
    password: "datapulse"
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.default_schema: datapulse
      hibernate.format_sql: true
      hibernate.jdbc.batch_size: 500
      hibernate.jdbc.fetch_size: 200
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.generate_statistics: false
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:/db/master.xml
    default-schema: datapulse
    liquibase-schema: datapulse

webclient:
  max-in-memory-size: 262144
  connect-timeout-millis: 10000
  response-timeout-seconds: 30
  read-timeout-seconds: 30
  write-timeout-seconds: 30

crypto:
  master-key-base64: ${DATAPULSE_CRYPTO_MASTER_KEY_BASE64:}
  gcm-tag-length-bits: 128

system-account:
  enabled: true
  name: DATAPULSE_SYSTEM
  connections:
    WILDBERRIES:
      active: true
      token: ${WB_SYSTEM_TOKEN:eyJhbGciOiJFUzI1NiIsImtpZCI6IjIwMjUwOTA0djEiLCJ0eXAiOiJKV1QifQ.eyJhY2MiOjIsImVudCI6MSwiZXhwIjoxNzc3MDU5Mzg0LCJpZCI6IjAxOWExNTI1LWI1ZmEtNzNiZi04ZWIwLTE3YjMwYjk1MGY2MCIsImlpZCI6MTI3MTk4NDEzLCJvaWQiOjI1MDA2MDg2MywicyI6MCwic2lkIjoiZTBhZWUxM2QtOTQ2Mi00Mjk5LTk2OTctNGY4YjRjYzQzMDY5IiwidCI6dHJ1ZSwidWlkIjoxMjcxOTg0MTN9.eURulaP5UTqegdGH86XJqRX2qnBao0jnX5DFCa_wUKzku84MCJF-IWyO6cdSokf6oVn5LPqtQkn-zLONagFvcg}
    OZON:
      active: true
      client-id: ${OZON_SYSTEM_CLIENT_ID:3528862}
      api-key: ${OZON_SYSTEM_API_KEY:e9e97944-6e3a-414a-aed1-9b547babac05}
