datapulse:
  integration:
    wildberries:
      content-base-url: http://${WIREMOCK_HOST:localhost}:${WIREMOCK_PORT:9091}
      prices-base-url: http://${WIREMOCK_HOST:localhost}:${WIREMOCK_PORT:9091}
      statistics-base-url: http://${WIREMOCK_HOST:localhost}:${WIREMOCK_PORT:9091}
      analytics-base-url: http://${WIREMOCK_HOST:localhost}:${WIREMOCK_PORT:9091}
      marketplace-base-url: http://${WIREMOCK_HOST:localhost}:${WIREMOCK_PORT:9091}
      advert-base-url: http://${WIREMOCK_HOST:localhost}:${WIREMOCK_PORT:9091}
      promo-base-url: http://${WIREMOCK_HOST:localhost}:${WIREMOCK_PORT:9091}
    ozon:
      seller-base-url: http://${WIREMOCK_HOST:localhost}:${WIREMOCK_PORT:9091}
      performance-base-url: http://${WIREMOCK_HOST:localhost}:${WIREMOCK_PORT:9091}

spring:
  jpa:
    show-sql: true

logging:
  level:
    io.datapulse: DEBUG
    org.springframework.security: DEBUG
