spring:
  config:
    activate:
      on-profile: local
marketplace:
  providers:
    WILDBERRIES:
      endpoints:
        DICT_WB_WAREHOUSES_FBW:
          url: https://supplies-api-sandbox.wildberries.ru/api/v1/warehouses
          authScope: SANDBOX_ACCOUNT
        DICT_WB_OFFICES_FBS:
          url: https://marketplace-api-sandbox.wildberries.ru/api/v3/offices
          authScope: SANDBOX_ACCOUNT
        DICT_WB_WAREHOUSES_SELLER:
          url: https://marketplace-api-sandbox.wildberries.ru/api/v3/warehouses
          authScope: SANDBOX_ACCOUNT
        DICT_WB_CATEGORIES_PARENT:
          url: https://content-api-sandbox.wildberries.ru/content/v2/object/parent/all
          authScope: SANDBOX_ACCOUNT
        DICT_WB_SUBJECTS:
          url: https://content-api-sandbox.wildberries.ru/content/v2/object/all
          authScope: SANDBOX_ACCOUNT
        DICT_WB_TARIFFS_COMMISSION:
          authScope: SYSTEM_ACCOUNT
    OZON:
      endpoints:
        DICT_OZON_WAREHOUSES_FBS:
          authScope: SYSTEM_ACCOUNT
        DICT_OZON_CLUSTERS:
          authScope: SYSTEM_ACCOUNT
        DICT_OZON_CATEGORY_TREE:
          authScope: SYSTEM_ACCOUNT
