marketplace:
  storage:
    base-dir: /var/datapulse/snapshots
    cleanup:
      max-age: 60s
      interval: 15s
  providers:
    WILDBERRIES:
      rateLimit:
        groups:
          WB_WAREHOUSES_FBW:
            limit: 2
            period: 20s
          WB_WAREHOUSES_FBS:
            limit: 300
            period: 60s
      endpoints:
        DICT_WB_WAREHOUSES_FBW:
          url: https://supplies-api-sandbox.wildberries.ru/api/v1/warehouses
          rateLimitGroup: WB_WAREHOUSES_FBW
        DICT_WB_OFFICES_FBS:
          url: https://marketplace-api-sandbox.wildberries.ru/api/v3/offices
          rateLimitGroup: WB_WAREHOUSES_FBS
        DICT_WB_WAREHOUSES_SELLER:
          url: https://marketplace-api-sandbox.wildberries.ru/api/v3/warehouses
          rateLimitGroup: WB_WAREHOUSES_FBS
      retryPolicy:
        maxAttempts: 3
        baseBackoff: 200ms
        maxBackoff: 30s
    OZON:
      endpoints:
        DICT_OZON_WAREHOUSES_FBS:
          url: https://api-seller.ozon.ru/v1/warehouse/list
        DICT_OZON_CLUSTERS:
          url: https://api-seller.ozon.ru/v1/cluster/list
      retryPolicy:
        maxAttempts: 4
        baseBackoff: 300ms
        maxBackoff: 20s
spring:
  cache:
    cache-names: marketplace-files
    caffeine:
      spec: maximumSize=500,expireAfterWrite=4h
