spring:
  application:
    name: datapulse
  datasource:
    url: jdbc:postgresql://localhost:5432/datapulse
    username: datapulse
    password: datapulse
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
      hibernate.show_sql: false
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: when_authorized