spring:
  rabbitmq:
    host: ${RABBIT_HOST:127.0.0.1}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USERNAME:client}
    password: ${RABBIT_PASSWORD:pasClient105}
    virtual-host: ${RABBIT_VHOST:datapulse}
    template:
      reply-timeout: 5s

etl:
  orchestrate:
    core-pool-size: 4
    max-pool-size: 8
