version: "3.9"

services:
  wb-mock:
    image: wiremock/wiremock:3.12.1
    container_name: datapulse-wb-mock
    ports:
      - "9090:8080"
    volumes:
      - ./wiremock/mappings:/home/wiremock/mappings:ro
      - ./wiremock/__files:/home/wiremock/__files:ro
    command:
      - "--verbose"
      - "--global-response-templating"
    restart: unless-stopped
