package io.datapulse.audit.domain;

public enum AlertRuleType {

    STALE_DATA,
    MISSING_SYNC,
    RESIDUAL_ANOMALY,
    SPIKE_DETECTION,
    MISMATCH,
    AD_DRR_THRESHOLD,
    AD_NO_STOCK,
    AD_INEFFICIENT_CAMPAIGN,
    AD_PRICE_DROP_HIGH_DRR,
    AUTOBID_HIGH_DRR_CLUSTER,
    AUTOBID_SPEND_SPIKE
}
